apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cloud-credential-operator-role
  namespace: uccp-cloud-credential-operator
  annotations:
    include.release.uccp.io/ibm-cloud-managed: "true"
    include.release.uccp.io/self-managed-high-availability: "true"
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  - events
  - serviceaccounts
  - services
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "*"
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - "*"
