apiVersion: v1
kind: Service
metadata:
  annotations:
    include.release.uccp.io/ibm-cloud-managed: "true"
    include.release.uccp.io/self-managed-high-availability: "true"
    service.alpha.uccp.io/serving-cert-secret-name: cloud-credential-operator-serving-cert
  name: cco-metrics
  namespace: uccp-cloud-credential-operator
spec:
  ports:
  - name: metrics
    port: 8443
    protocol: TCP
    targetPort: metrics
  selector:
    app: cloud-credential-operator
  sessionAffinity: None
  type: ClusterIP
