apiVersion: v1
kind: Service
metadata:
  annotations:
    include.release.uccp.io/self-managed-high-availability: "true"
    release.uccp.io/delete: "true"
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  name: controller-manager-service
  namespace: uccp-cloud-credential-operator
spec:
  ports:
  - port: 443
  selector:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
