apiVersion: cloudcredential.uccp.io/v1
kind: CredentialsRequest
metadata:
  name: cloud-credential-operator-gcp-ro-creds
  namespace: uccp-cloud-credential-operator
  annotations:
    exclude.release.uccp.io/internal-uccp-hosted: "true"
    include.release.uccp.io/self-managed-high-availability: "true"
spec:
  providerSpec:
    apiVersion: cloudcredential.uccp.io/v1
    kind: GCPProviderSpec
    predefinedRoles:
    - roles/iam.securityReviewer
    - roles/iam.roleViewer
    skipServiceCheck: true
  secretRef:
    name: cloud-credential-operator-gcp-ro-creds
    namespace: uccp-cloud-credential-operator
  serviceAccountNames:
  - cloud-credential-operator
  
