apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pod-identity-webhook
  annotations:
    service.beta.uccp.io/inject-cabundle: "true"
webhooks:
- name: pod-identity-webhook.amazonaws.com
  admissionReviewVersions:
  - v1beta1
  failurePolicy: Ignore
  sideEffects: None
  clientConfig:
    service:
      name: pod-identity-webhook
      namespace: uccp-cloud-credential-operator
      path: "/mutate"
  namespaceSelector:
    matchExpressions:
    - key: uccp.io/run-level
      operator: NotIn
      values:
      - "0"
  rules:
  - operations: [ "CREATE" ]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
